/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TourCategory = IDL.Variant({
  'antarctica' : IDL.Null,
  'featured' : IDL.Null,
  'latinAmerica' : IDL.Null,
  'adventure' : IDL.Null,
  'luxury' : IDL.Null,
});
export const Tour = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Record({ 'days' : IDL.Nat, 'nights' : IDL.Nat }),
  'departureInfo' : IDL.Text,
  'category' : TourCategory,
  'badge' : IDL.Opt(IDL.Text),
  'image' : IDL.Text,
  'priceCNY' : IDL.Nat,
  'location' : IDL.Text,
});
export const Destination = IDL.Record({
  'region' : IDL.Text,
  'name' : IDL.Text,
  'routeCount' : IDL.Nat,
});
export const GuideCategory = IDL.Variant({
  'sightseeing' : IDL.Null,
  'cultural' : IDL.Null,
  'adventure' : IDL.Null,
  'wildlife' : IDL.Null,
  'luxury' : IDL.Null,
  'relaxation' : IDL.Null,
  'family' : IDL.Null,
  'photography' : IDL.Null,
});
export const Guide = IDL.Record({
  'title' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : GuideCategory,
});

export const idlService = IDL.Service({
  'getAllToursByCategory' : IDL.Func(
      [TourCategory],
      [IDL.Vec(Tour)],
      ['query'],
    ),
  'getAllToursSortedByPrice' : IDL.Func([], [IDL.Vec(Tour)], ['query']),
  'getDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
  'getDestinationsByRegion' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Destination)],
      ['query'],
    ),
  'getDestinationsSortedByRouteCount' : IDL.Func(
      [],
      [IDL.Vec(Destination)],
      ['query'],
    ),
  'getGuides' : IDL.Func([], [IDL.Vec(Guide)], ['query']),
  'getGuidesByCategory' : IDL.Func(
      [GuideCategory],
      [IDL.Vec(Guide)],
      ['query'],
    ),
  'getTours' : IDL.Func([], [IDL.Vec(Tour)], ['query']),
  'getToursByCategory' : IDL.Func([TourCategory], [IDL.Vec(Tour)], ['query']),
  'getToursByPriceRange' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Tour)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TourCategory = IDL.Variant({
    'antarctica' : IDL.Null,
    'featured' : IDL.Null,
    'latinAmerica' : IDL.Null,
    'adventure' : IDL.Null,
    'luxury' : IDL.Null,
  });
  const Tour = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Record({ 'days' : IDL.Nat, 'nights' : IDL.Nat }),
    'departureInfo' : IDL.Text,
    'category' : TourCategory,
    'badge' : IDL.Opt(IDL.Text),
    'image' : IDL.Text,
    'priceCNY' : IDL.Nat,
    'location' : IDL.Text,
  });
  const Destination = IDL.Record({
    'region' : IDL.Text,
    'name' : IDL.Text,
    'routeCount' : IDL.Nat,
  });
  const GuideCategory = IDL.Variant({
    'sightseeing' : IDL.Null,
    'cultural' : IDL.Null,
    'adventure' : IDL.Null,
    'wildlife' : IDL.Null,
    'luxury' : IDL.Null,
    'relaxation' : IDL.Null,
    'family' : IDL.Null,
    'photography' : IDL.Null,
  });
  const Guide = IDL.Record({
    'title' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : GuideCategory,
  });
  
  return IDL.Service({
    'getAllToursByCategory' : IDL.Func(
        [TourCategory],
        [IDL.Vec(Tour)],
        ['query'],
      ),
    'getAllToursSortedByPrice' : IDL.Func([], [IDL.Vec(Tour)], ['query']),
    'getDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
    'getDestinationsByRegion' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Destination)],
        ['query'],
      ),
    'getDestinationsSortedByRouteCount' : IDL.Func(
        [],
        [IDL.Vec(Destination)],
        ['query'],
      ),
    'getGuides' : IDL.Func([], [IDL.Vec(Guide)], ['query']),
    'getGuidesByCategory' : IDL.Func(
        [GuideCategory],
        [IDL.Vec(Guide)],
        ['query'],
      ),
    'getTours' : IDL.Func([], [IDL.Vec(Tour)], ['query']),
    'getToursByCategory' : IDL.Func([TourCategory], [IDL.Vec(Tour)], ['query']),
    'getToursByPriceRange' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Tour)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };