/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Destination {
  'region' : string,
  'name' : string,
  'routeCount' : bigint,
}
export interface Guide {
  'title' : string,
  'excerpt' : string,
  'category' : GuideCategory,
}
export type GuideCategory = { 'sightseeing' : null } |
  { 'cultural' : null } |
  { 'adventure' : null } |
  { 'wildlife' : null } |
  { 'luxury' : null } |
  { 'relaxation' : null } |
  { 'family' : null } |
  { 'photography' : null };
export interface Tour {
  'title' : string,
  'duration' : { 'days' : bigint, 'nights' : bigint },
  'departureInfo' : string,
  'category' : TourCategory,
  'badge' : [] | [string],
  'image' : string,
  'priceCNY' : bigint,
  'location' : string,
}
export type TourCategory = { 'antarctica' : null } |
  { 'featured' : null } |
  { 'latinAmerica' : null } |
  { 'adventure' : null } |
  { 'luxury' : null };
export interface _SERVICE {
  'getAllToursByCategory' : ActorMethod<[TourCategory], Array<Tour>>,
  'getAllToursSortedByPrice' : ActorMethod<[], Array<Tour>>,
  'getDestinations' : ActorMethod<[], Array<Destination>>,
  'getDestinationsByRegion' : ActorMethod<[string], Array<Destination>>,
  'getDestinationsSortedByRouteCount' : ActorMethod<[], Array<Destination>>,
  'getGuides' : ActorMethod<[], Array<Guide>>,
  'getGuidesByCategory' : ActorMethod<[GuideCategory], Array<Guide>>,
  'getTours' : ActorMethod<[], Array<Tour>>,
  'getToursByCategory' : ActorMethod<[TourCategory], Array<Tour>>,
  'getToursByPriceRange' : ActorMethod<[bigint, bigint], Array<Tour>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];