/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Tour {
    title: string;
    duration: {
        days: bigint;
        nights: bigint;
    };
    departureInfo: string;
    category: TourCategory;
    badge?: string;
    image: string;
    priceCNY: bigint;
    location: string;
}
export interface Guide {
    title: string;
    excerpt: string;
    category: GuideCategory;
}
export interface Destination {
    region: string;
    name: string;
    routeCount: bigint;
}
export enum GuideCategory {
    sightseeing = "sightseeing",
    cultural = "cultural",
    adventure = "adventure",
    wildlife = "wildlife",
    luxury = "luxury",
    relaxation = "relaxation",
    family = "family",
    photography = "photography"
}
export enum TourCategory {
    antarctica = "antarctica",
    featured = "featured",
    latinAmerica = "latinAmerica",
    adventure = "adventure",
    luxury = "luxury"
}
export interface backendInterface {
    getAllToursByCategory(category: TourCategory): Promise<Array<Tour>>;
    getAllToursSortedByPrice(): Promise<Array<Tour>>;
    getDestinations(): Promise<Array<Destination>>;
    getDestinationsByRegion(region: string): Promise<Array<Destination>>;
    getDestinationsSortedByRouteCount(): Promise<Array<Destination>>;
    getGuides(): Promise<Array<Guide>>;
    getGuidesByCategory(category: GuideCategory): Promise<Array<Guide>>;
    getTours(): Promise<Array<Tour>>;
    getToursByCategory(category: TourCategory): Promise<Array<Tour>>;
    getToursByPriceRange(minPrice: bigint, maxPrice: bigint): Promise<Array<Tour>>;
}
import type { Guide as _Guide, GuideCategory as _GuideCategory, Tour as _Tour, TourCategory as _TourCategory } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllToursByCategory(arg0: TourCategory): Promise<Array<Tour>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllToursByCategory(to_candid_TourCategory_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllToursByCategory(to_candid_TourCategory_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllToursSortedByPrice(): Promise<Array<Tour>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllToursSortedByPrice();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllToursSortedByPrice();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDestinations(): Promise<Array<Destination>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDestinations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDestinations();
            return result;
        }
    }
    async getDestinationsByRegion(arg0: string): Promise<Array<Destination>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDestinationsByRegion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDestinationsByRegion(arg0);
            return result;
        }
    }
    async getDestinationsSortedByRouteCount(): Promise<Array<Destination>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDestinationsSortedByRouteCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDestinationsSortedByRouteCount();
            return result;
        }
    }
    async getGuides(): Promise<Array<Guide>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGuides();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGuides();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGuidesByCategory(arg0: GuideCategory): Promise<Array<Guide>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGuidesByCategory(to_candid_GuideCategory_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGuidesByCategory(to_candid_GuideCategory_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTours(): Promise<Array<Tour>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTours();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTours();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getToursByCategory(arg0: TourCategory): Promise<Array<Tour>> {
        if (this.processError) {
            try {
                const result = await this.actor.getToursByCategory(to_candid_TourCategory_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getToursByCategory(to_candid_TourCategory_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getToursByPriceRange(arg0: bigint, arg1: bigint): Promise<Array<Tour>> {
        if (this.processError) {
            try {
                const result = await this.actor.getToursByPriceRange(arg0, arg1);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getToursByPriceRange(arg0, arg1);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_GuideCategory_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GuideCategory): GuideCategory {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Guide_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Guide): Guide {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_TourCategory_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TourCategory): TourCategory {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Tour_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tour): Tour {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    excerpt: string;
    category: _GuideCategory;
}): {
    title: string;
    excerpt: string;
    category: GuideCategory;
} {
    return {
        title: value.title,
        excerpt: value.excerpt,
        category: from_candid_GuideCategory_n12(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    duration: {
        days: bigint;
        nights: bigint;
    };
    departureInfo: string;
    category: _TourCategory;
    badge: [] | [string];
    image: string;
    priceCNY: bigint;
    location: string;
}): {
    title: string;
    duration: {
        days: bigint;
        nights: bigint;
    };
    departureInfo: string;
    category: TourCategory;
    badge?: string;
    image: string;
    priceCNY: bigint;
    location: string;
} {
    return {
        title: value.title,
        duration: value.duration,
        departureInfo: value.departureInfo,
        category: from_candid_TourCategory_n6(_uploadFile, _downloadFile, value.category),
        badge: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.badge)),
        image: value.image,
        priceCNY: value.priceCNY,
        location: value.location
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sightseeing: null;
} | {
    cultural: null;
} | {
    adventure: null;
} | {
    wildlife: null;
} | {
    luxury: null;
} | {
    relaxation: null;
} | {
    family: null;
} | {
    photography: null;
}): GuideCategory {
    return "sightseeing" in value ? GuideCategory.sightseeing : "cultural" in value ? GuideCategory.cultural : "adventure" in value ? GuideCategory.adventure : "wildlife" in value ? GuideCategory.wildlife : "luxury" in value ? GuideCategory.luxury : "relaxation" in value ? GuideCategory.relaxation : "family" in value ? GuideCategory.family : "photography" in value ? GuideCategory.photography : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    antarctica: null;
} | {
    featured: null;
} | {
    latinAmerica: null;
} | {
    adventure: null;
} | {
    luxury: null;
}): TourCategory {
    return "antarctica" in value ? TourCategory.antarctica : "featured" in value ? TourCategory.featured : "latinAmerica" in value ? TourCategory.latinAmerica : "adventure" in value ? TourCategory.adventure : "luxury" in value ? TourCategory.luxury : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Tour>): Array<Tour> {
    return value.map((x)=>from_candid_Tour_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Guide>): Array<Guide> {
    return value.map((x)=>from_candid_Guide_n10(_uploadFile, _downloadFile, x));
}
function to_candid_GuideCategory_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GuideCategory): _GuideCategory {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_TourCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TourCategory): _TourCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GuideCategory): {
    sightseeing: null;
} | {
    cultural: null;
} | {
    adventure: null;
} | {
    wildlife: null;
} | {
    luxury: null;
} | {
    relaxation: null;
} | {
    family: null;
} | {
    photography: null;
} {
    return value == GuideCategory.sightseeing ? {
        sightseeing: null
    } : value == GuideCategory.cultural ? {
        cultural: null
    } : value == GuideCategory.adventure ? {
        adventure: null
    } : value == GuideCategory.wildlife ? {
        wildlife: null
    } : value == GuideCategory.luxury ? {
        luxury: null
    } : value == GuideCategory.relaxation ? {
        relaxation: null
    } : value == GuideCategory.family ? {
        family: null
    } : value == GuideCategory.photography ? {
        photography: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TourCategory): {
    antarctica: null;
} | {
    featured: null;
} | {
    latinAmerica: null;
} | {
    adventure: null;
} | {
    luxury: null;
} {
    return value == TourCategory.antarctica ? {
        antarctica: null
    } : value == TourCategory.featured ? {
        featured: null
    } : value == TourCategory.latinAmerica ? {
        latinAmerica: null
    } : value == TourCategory.adventure ? {
        adventure: null
    } : value == TourCategory.luxury ? {
        luxury: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
